name: aipply
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  device_preview: ^1.3.1
  flutter_riverpod: ^2.6.1
  go_router: ^14.8.1
  intl: any
  fluttertoast: ^9.0.0
  shared_preferences: ^2.5.3
  dio: ^5.9.0
  http: ^1.5.0
  dropdown_button2: ^2.3.9
  image_picker: ^1.2.0
  path: ^1.9.1
  path_provider: ^2.1.5
  cached_network_image: ^3.4.1
  flutter_localizations:
    sdk: flutter
  html_editor_enhanced: ^2.7.1
  pdf: ^3.11.3
  printing: ^5.14.2
  universal_html: ^2.2.4
  flutter_html_to_pdf: ^0.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/fonts/
    - assets/images/
    - assets/images/core/

  fonts:
    - family: 'Proxima Nova'
      fonts:
        - asset: assets/fonts/Lato_Light.ttf
        - asset: assets/fonts/Lato_Regular.ttf
        - asset: assets/fonts/Poppins_Bold.ttf

